version: '3'

services:
  langchain:
    image: yeardream-langchain:latest
    container_name: langchain
    build: .
    # ports:
    #   - "8888:8888"
    volumes:
      - ./:/app
    networks:
      - default
    restart: unless-stopped

  sqlitebrowser:
    image: lscr.io/linuxserver/sqlitebrowser:latest
    container_name: sqlite
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
    volumes:
      - ./database:/config
    networks:
      - default
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped

networks:
  default: