version: '3'

services:
  langchain:
    image: yeardream-langchain:latest
    container_name: langchain
    build: .
    # ports:
    #   - "8888:8888"
    volumes:
      - ./:/app
    networks:
      - default
    restart: always

  sqlite:
    image: nouchka/sqlite3:latest
    container_name: sqlite
    volumes:
      - ./database:/var/lib/sqlite
    networks:
      - default
    restart: always

networks:
  default: